#启动: nohup java  -jar  xxx.jar >  log.admin 2>&1 &
server:
  port: 8090
  compression:
    enabled: true
  connection-timeout: 3000
spring:
  redis:
      host: 192.168.0.105
      port: 6379
  datasource:
      url: jdbc:mysql://192.168.0.105:3306/spring-cache?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
      username: root
      password: 11111
      driverClassName : com.mysql.jdbc.Driver
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
mybatis:
  mapperLocations: classpath:mapper/*.xml

#logging:
#  level:
#    org:
#      example:
#        cache:  debug



